{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "common.names.fullname" . }}
spec:
  selector:
    istio: {{ .Values.istio.ingressController.name }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ .Values.istio.host }} 
{{- end }}
