apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  IDENTITY_BASE_URL: {{.Values.global.base_urls.identity | quote}}
  WEB_DID_BASE_URL: {{.Values.global.base_urls.web_did | quote}}
  SCHEMA_BASE_URL: {{.Values.global.base_urls.credential_schema | quote}}
  CREDENTIAL_SERVICE_BASE_URL: {{.Values.global.base_urls.credential_service | quote}}
  JWKS_URI: {{.Values.global.sunbird.jwks_uri | quote}}
  ENABLE_AUTH: {{.Values.global.sunbird.enable_auth | quote}}
  VAULT_ADDR: {{.Values.global.vault.address | quote}} 
  VAULT_BASE_URL: {{.Values.global.vault.base_url | quote}}
  VAULT_ROOT_PATH: {{.Values.global.vault.root_path | quote}}
  VAULT_TIMEOUT: {{.Values.global.vault.vault_timeout | quote}}
  VAULT_PROXY: {{.Values.global.vault.vault_proxy | quote}}
  SIGNING_ALGORITHM: {{.Values.global.sunbird.signing_algo | quote}}


