imagepullsecrets: 
dockerhub: ghcr.io/sunbird-rc

replicaCount: 1
repository: sunbird-rc-core
image_tag: v2.0.0-rc1
resources: {}
network:
  port: 8081
  targetport: 8081
strategy:
  type: RollingUpdate
  maxsurge: '50%'
  maxunavailable: '50%'

autoscaling:
  enabled: 'false'
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80

rccoreenv:
  connectionInfo_uri: ""
  connectionInfo_username: registry
  connectionInfo_password: ""
  encryption_enabled: false
  encryption_health_check_url: http://encryption-service:8013/health
  encryption_uri: http://encryption-service:8013/crypto/v1/_encrypt
  encryption_batch_uri: http://encryption-service:8013/crypto/v1/_encrypt
  event_enabled: false
  event_topic: events
  event_providerName: dev.sunbirdrc.registry.service.impl.KafkaEventService 
  elastic_search_enabled: True
  elastic_search_connection_url: elasticsearch-master:9200
  elastic_search_scheme: http
  elastic_search_auth_enabled: false
  elastic_search_username: elastic
  elastic_search_password: elastic
  search_provider: "dev.sunbirdrc.registry.service.ElasticSearchService"
  search_providerName: dev.sunbirdrc.registry.service.NativeSearchService
  sunbird_sso_realm: sunbird-rc
  sunbird_sso_url: http://keycloak:8080/auth
  oauth2_resource_uri: http://keycloak:8080/auth/realms/sunbird-rc
  oauth2_resource_roles_path: realm_access.roles
  identity_provider: dev.sunbirdrc.auth.keycloak.KeycloakProviderImpl
  idgen_enabled: false
  idgen_health_check_url: http://id-gen-service:8088/egov-idgen/health
  idgen_generate_url: http://id-gen-service:8088/egov-idgen/id/_generate
  idgen_id_format_url: http://id-gen-service:8088/egov-idgen/id/_format/add
  sunbird_sso_admin_client_id: 'admin-api'
  sunbird_sso_client_id: 'registry-frontend'
  sunbird_sso_admin_client_secret: ""
  claims_enabled: false
  claims_url: http://claim-ms:8082
  did_enabled: True
  did_health_check_url: http://identity-identity-service:3332/health 
  did_generate_url: http://identity-identity-service:3332/did/generate  
  did_resolve_url: http://identity-identity-service:3332/did/resolve  
  signature_enabled: false
  signature_provider: dev.sunbirdrc.registry.service.impl.SignatureV2ServiceImpl
  signature_v2_health_check_url: http://credential:3000/health
  signature_v2_issue_url: http://credential:3000/credentials/issue
  signature_v2_get_url: http://credential:3000/credentials/{id}
  signature_v2_delete_url: http://credential:3000/credentials/{id}
  signature_v2_verify_url:  http://credential:3000/credentials/{id}/verify
  signature_v2_revocation_list_url: http://credential:3000/credentials/revocation-list?issuerId={issuerDid}&page={page}&limit={limit}
  signature_v2_schema_health_check_url: http://schema:3333/health
  signature_v2_schema_create_url: http://schema:3333/credential-schema
  signature_v2_schema_update_url: "http://schema:3333/credential-schema/{id}/{version}"
  signature_v2_schema_get_by_id_and_version_url: "http://schema:3333/credential-schema/{id}/{version}"
  signature_v2_schema_search_by_tags_url: "http://schema:3333/credential-schema?tags={tags}"
  sign_url: http://certificate-signer:8079/sign
  verify_url: http://certificate-signer:8079/verify
  sign_health_check_url: http://certificate-signer:8079/health
  certificate_enabled: false 
  pdf_url: http://certificate-api:8078/api/v1/certificatePDF
  certificate_health_check_url: http://certificate-api:8078/health
  template_base_url: http://registry:8081/api/v1/templates/ #Looks for certificate templates for pdf copy of the signed certificate
  sunbird_keycloak_user_set_password: true
  filestorage_enabled: false 
  filestorage_connection_url: http://file-storage:9000
  filestorage_access_key: admin
  filestorage_secret_key: ""
  filestorage_bucket_key: issuance
  registry_base_apis_enable: false
  sunbird_keycloak_user_password: abcd@123 
  logging.level.root: INFO
  enable_external_templates: true
  async_enabled: false
  authentication_enabled: true
  kafka_bootstrap_address: kafka:9092
  webhook_enabled: false
  webhook_url: http://localhost:5001/api/v1/callback
  redis_host: redis
  redis_port: 6379
  manager_type:  DefinitionsManager
  expand_reference: false
  swagger_title: Sunbird Registry and Credential
  notification_async_enabled:  false
  notification_enabled: false
  notification_url: http://notification-ms:8765/notification-service/v1/notification
  workflow.enable: 'false'
  connectionInfo_maxPoolSize: '200'
  auditTaskExecutor_queueCapacity: '100'
  taskExecutor_index_queueCapacity: '100'


serviceMonitor:
  enabled: true
  labels: # labels with which the prometheus choose the serviceMonitor
    app: prometheus-operator
    release: prometheus-operator
