---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
     rollingUpdate:
        maxSurge: {{ .Values.strategy.maxsurge }}
        maxUnavailable: {{ .Values.strategy.maxunavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
{{- if .Values.imagepullsecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagepullsecrets }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.network.port }}
        readinessProbe:
          httpGet:
            path: /auth/
            port: {{ .Values.network.port }}
          failureThreshold: 10
          periodSeconds: 30
          timeoutSeconds: 10
          initialDelaySeconds: 30
        livenessProbe:
          tcpSocket:
            port: {{ .Values.network.port }}
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 10
        volumeMounts:
        - name: {{ .Chart.Name }}-conf
          mountPath: /opt/jboss/keycloak/imports/
      volumes:
      - name: {{ .Chart.Name }}-conf
        configMap:
          name: {{ .Chart.Name }}-conf       

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: http-{{ .Chart.Name }}
    protocol: TCP
    port: {{ .Values.network.targetport }}
  selector:
    app: {{ .Chart.Name }}
