apiVersion: v2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart to installed Downloader for Regstration Client Application
home: https://mosip.io
keywords:
- mosip
- landing-page
- registration
- client
maintainers:
- email: info@mosip.io
  name: MOSIP
name: landing-page
type: application
version: 12.0.1
