apiVersion: v1
data:
  {{- range $key, $val := .Values.filestorageenv }}
  {{ $key }}: |-
{{ $val| indent 4 }}
  {{- end }}
kind: ConfigMap 
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
