apiVersion: v2
appVersion: 2.6.2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: a multi-protocol, embeddable, very high performance, clustered, asynchronous
  messaging system.
home: https://activemq.apache.org/artemis/
icon: https://activemq.apache.org/assets/img/activemq_logo_icon.png
keywords:
- activemq
- artemis
- messaging
- mom
- amqp
- jms
- mqtt
maintainers:
- email: victor.romero@gmail.com
  name: vromero
name: activemq-artemis
sources:
- https://github.com/kubernetes/charts
- https://github.com/apache/activemq-artemis
version: 0.0.2
