apiVersion: v2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for MOSIP inji-certify module
home: https://mosip.io
keywords:
- mosip
- inji-certify
maintainers:
- email: info@mosip.io
  name: MOSIP
name: inji-certify
type: application
version: 0.10.2
