# Default values for registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: beckn-onix-bpp
  image:
    repository: fidedocker/protocol-server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: ""

# Redis connection details
  redisCache:
    host: redis-master.bpp-common-services.svc.cluster.local
    port: 6379

# Mongodb connection details
  responseCacheMongo:
    host: mongodb.bpp-common-services.svc.cluster.local
    port: 27017
    dbname: protocol_server
    username: root
    password:

# RabbitMQ connection details
  rabbitMQamqp:
    host: rabbitmq.bpp-common-services.svc.cluster.local
    port: 5672
    username: beckn
    password:

  # Istio Ingress Definitions
  istio:
    enabled: true 
    gateway: "istio-system/all-hosts"

# Must be set while installing Helm chart
  externalDomain: example.com
  registry_url: registry.example.com
  bpp:
    privateKey: "private-key"
    publicKey: "public-key"


# BPP subscribe_id. Default to externalDomain value.
  subscriber_id:

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  nodeSelector: {}

  tolerations: []

  affinity: {}

  ## Storage class with read write many supported e.g longhorn
  persistence:
    storageClassName: 
    size: 1Gi