apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $index, $client := .Values.clientSecrets }}
  {{- if $client.secret }}
  {{ $client.name }}: {{ $client.secret | b64enc | quote }}
  {{- else }}
  {{ $client.name }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }} 
  {{- end }} 
  

