apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beckn-onix-bap-efs-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.global.persistence.size }}