apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.name" . }}-logs-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.persistence.size }}
  storageClassName: {{ .Values.global.persistence.storageClassName }}
